terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    random = {
      source = "hashicorp/random"
    }
  }
}

variable "project" {
  type        = string
  description = "Project name used for resource names."
}

variable "environment" {
  type        = string
  description = "Environment name such as dev or prod."
}

variable "db_identifier" {
  type        = string
  description = "RDS instance identifier."
}

variable "db_name" {
  type        = string
  description = "Initial database name."
  default     = "fintech"
}

variable "db_username" {
  type        = string
  description = "Master database username. Password is generated by RDS Secrets Manager."
  default     = "postgres"
}

variable "engine_version" {
  type        = string
  description = "PostgreSQL engine version."
  default     = "16.3"
}

variable "instance_class" {
  type        = string
  description = "RDS instance class."
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  type        = number
  description = "Initial RDS storage in GiB."
  default     = 20
}

variable "max_allocated_storage" {
  type        = number
  description = "Maximum autoscaled RDS storage in GiB."
  default     = 100
}

variable "vpc_id" {
  type        = string
  description = "VPC ID for the database security group."
}

variable "database_subnet_ids" {
  type        = list(string)
  description = "Private database subnet IDs."
}

variable "allowed_security_group_ids" {
  type        = list(string)
  description = "Security groups allowed to connect to PostgreSQL."
}

variable "multi_az" {
  type        = bool
  description = "Enable Multi-AZ RDS for high availability."
  default     = true
}

variable "backup_retention_period" {
  type        = number
  description = "Number of days to retain backups."
  default     = 7
}

variable "deletion_protection" {
  type        = bool
  description = "Protect production databases from accidental deletion."
  default     = true
}

variable "replicate_source_db" {
  type        = string
  description = "Source DB ARN/identifier when creating a cross-region read replica."
  default     = null
}

variable "kms_key_id" {
  type        = string
  description = "KMS key ARN used to encrypt the DB instance. Required for encrypted cross-region read replicas."
  default     = null
}

variable "common_tags" {
  type        = map(string)
  description = "Common tags applied to DB resources."
  default     = {}
}

locals {
  is_replica = var.replicate_source_db != null
  name = "${var.project}-${var.environment}"
  tags = merge(var.common_tags, {
    Project     = var.project
    Environment = var.environment
    ManagedBy   = "terraform"
  })
}

resource "random_password" "master" {
  count   = local.is_replica ? 0 : 1
  length  = 20
  special = false
}

resource "aws_db_subnet_group" "this" {
  name       = "${local.name}-db-subnets"
  subnet_ids = var.database_subnet_ids

  tags = merge(local.tags, {
    Name = "${local.name}-db-subnets"
  })
}

resource "aws_security_group" "db" {
  name        = "${local.name}-db-sg"
  description = "Allow PostgreSQL only from application security groups"
  vpc_id      = var.vpc_id

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(local.tags, {
    Name = "${local.name}-db-sg"
  })
}

resource "aws_security_group_rule" "postgres_ingress" {
  for_each                 = { for index, security_group_id in var.allowed_security_group_ids : index => security_group_id }
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  security_group_id        = aws_security_group.db.id
  source_security_group_id = each.value
}

resource "aws_db_instance" "this" {
  identifier = var.db_identifier

  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_encrypted     = true
  kms_key_id            = var.kms_key_id

  db_name                     = local.is_replica ? null : var.db_name
  username                    = local.is_replica ? null : var.db_username
  password                    = local.is_replica ? null : random_password.master[0].result
  replicate_source_db         = var.replicate_source_db

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.db.id]
  publicly_accessible    = false
  multi_az               = local.is_replica ? false : var.multi_az

  backup_retention_period   = var.backup_retention_period
  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.deletion_protection ? false : true
  final_snapshot_identifier = var.deletion_protection ? "${var.db_identifier}-final-snapshot" : null

  tags = merge(local.tags, {
    Name = var.db_identifier
  })
}

resource "aws_secretsmanager_secret" "db_credentials" {
  count                   = local.is_replica ? 0 : 1
  name                    = "${local.name}/${var.db_identifier}/credentials"
  recovery_window_in_days = var.deletion_protection ? 7 : 0

  tags = merge(local.tags, {
    Name = "${local.name}-db-credentials"
  })
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  count     = local.is_replica ? 0 : 1
  secret_id = aws_secretsmanager_secret.db_credentials[0].id

  secret_string = jsonencode({
    username = var.db_username
    password = random_password.master[0].result
    host     = aws_db_instance.this.address
    port     = 5432
    dbname   = var.db_name
  })
}

output "db_instance_arn" {
  value = aws_db_instance.this.arn
}

output "db_address" {
  value = aws_db_instance.this.address
}

output "db_endpoint" {
  value = aws_db_instance.this.endpoint
}

output "db_security_group_id" {
  value = aws_security_group.db.id
}

output "master_user_secret_arn" {
  value = try(aws_secretsmanager_secret.db_credentials[0].arn, null)
}
