apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fintech
type: Opaque
stringData:
  POSTGRES_DB: fintech
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: CHANGE_ME_FOR_DEV_ONLY
  DB_HOST: postgres.fintech.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: fintech
  DB_USER: postgres
  DB_PASSWORD: CHANGE_ME_FOR_DEV_ONLY
  DB_SSL: "false"
